import type { Category } from "@/shared/domain/category";

export const CATEGORY_KEYWORDS: Record<Category, string[]> = {
  Rent: [
    "rent",
    "rental",
    "landlord",
    "apartment",
    "condo",
    "housing",
    "mortgage",
    "hoa",
    "property",
  ],
  Electricity: [
    "electric",
    "electricity",
    "power",
    "energy",
    "utility",
    "utilities",
  ],
  Water: ["water", "sewer", "sanitation", "trash", "garbage", "waste"],
  Internet: [
    "internet",
    "wifi",
    "broadband",
    "cable",
    "phone",
    "telephone",
    "mobile",
    "cellular",
    "telecom",
  ],
  Groceries: [
    "grocery",
    "groceries",
    "supermarket",
    "market",
    "food store",
    "walmart",
    "costco",
    "aldi",
    "lidl",
  ],
  Fuel: [
    "fuel",
    "gas station",
    "gasoline",
    "petrol",
    "diesel",
    "shell",
    "chevron",
    "bp",
  ],
  Insurance: [
    "insurance",
    "insurer",
    "policy",
    "life insurance",
    "auto insurance",
    "home insurance",
  ],
  Medical: [
    "medical",
    "health",
    "healthcare",
    "doctor",
    "physician",
    "hospital",
    "clinic",
    "pharmacy",
    "prescription",
    "dental",
    "dentist",
    "vision",
    "optometrist",
  ],
  Streaming: [
    "netflix",
    "spotify",
    "hulu",
    "disney",
    "disney+",
    "hbo",
    "max",
    "paramount",
    "peacock",
    "youtube",
    "prime video",
    "streaming",
    "subscription",
    "apple music",
    "apple tv",
  ],
  Dining: [
    "restaurant",
    "dining",
    "cafe",
    "coffee",
    "starbucks",
    "bakery",
    "pizza",
    "takeout",
    "fast food",
    "doordash",
    "ubereats",
    "grubhub",
    "delivery",
  ],
  Entertainment: [
    "movie",
    "movies",
    "cinema",
    "theater",
    "concert",
    "ticket",
    "tickets",
    "game",
    "games",
    "gaming",
    "entertainment",
    "recreation",
    "sports",
  ],
  Uncategorized: [],
};
