export const EXPENSE_IMPORT_E2E = [
  "expense-import.title",
  "expense-import.dropzone",
  "expense-import.dropzone.processing",
  "expense-import.dropzone.errors",
  "expense-import.stats",
  "expense-import.stats.errors",
  "expense-import.stats.duplicates",
  "expense-import.table",
  "expense-import.row.error",
  "expense-import.row.duplicate",
  "expense-import.bulk-actions",
  "expense-import.bulk-actions.remove-errors",
  "expense-import.bulk-actions.remove-duplicates",
  "expense-import.button.cancel",
  "expense-import.button.finalize",
  "expense-import.state.success",
  "expense-import.state.error",
] as const;
